### ISSUE TITLE
xBus.addListener() support

### ISSUE THREAD

**Issue by PaintNinja** [Matyrobbrt/GroovyModLoader#13]
It would be nice if GML supported using modBus/forgeBus.addListener(), particularly for script mods where it would result in less boilerplate for event subscriptions.

```groovy
modBus.addListener { FMLClientSetupEvent event ->
    log.info 'Hello from FMLClientSetupEvent'
}
```

**Comment by Matyrobbrt** [comment]
Should be trivial to do considering that Eventbus *finally* has api methods for explicit event types.
