### ISSUE TITLE
runClient run config doesn't include GML

### ISSUE THREAD

**Issue by PaintNinja** [Matyrobbrt/GroovyModLoader#15]
To reproduce:
1. Clone the repo to a new folder
2. Import into IntelliJ and wait for it to setup
3. Run the `genIntellijRuns` task
4. Run the `runClient` IDE run config
5. Observe that the mods menu and logs are missing GML

A temporary workaround is to manually run the `fullJar` task before each run.

**Comment by Matyrobbrt** [comment]
IDE run configurations cannot be supported due to needing to build another jar. Use the gradle run tasks.
