### ISSUE TITLE
GML Crash startup Valhelsia 6 Modpack

### ISSUE THREAD

**Issue by Sorairei** [Matyrobbrt/GroovyModLoader#24]
When minecraft modpack its loading mods crash and send me a crash error:

_The game crashed whilst initializing game
Error: java.net.ConnectException: null
Código de error: -1_

here is my crash log report:

[crash-2023-11-11_12.19.06-client.txt](https://github.com/GroovyMC/GroovyModLoader/files/13326205/crash-2023-11-11_12.19.06-client.txt)

Admin in valhelsia discord told me this:

![valhelsia](https://github.com/GroovyMC/GroovyModLoader/assets/79299476/6771f09b-4e66-4299-ab3a-cdf2987ab17e)

I tried disabled all firewalls and nothing happends, i don't know what can be :( .

I have Windows 11 and instaled via Curseforge, later manual and its the same result.

**Comment by Sorairei** [comment]
nevermind for some reason disabling IPv6 worked fine :D

https://support.curseforge.com/en/support/solutions/articles/9000194900-curseforge-troubleshooting#IPv6

**Comment by lukebemish** [comment]
That's a weird one. GML grabs some files from Mojang for runtime remapping; they've been having some weirdness with their servers lately so I'm going to blame this on that but I'm not entirely sure
