### ISSUE TITLE
Crash on launch in production due to `PackMCMetaVersionsGetter` failing

### ISSUE THREAD

**Issue by PaintNinja** [Matyrobbrt/GroovyModLoader#9]
https://mclo.gs/sobKI41

https://github.com/Matyrobbrt/GroovyModLoader/blob/main/src/mod/groovy/com/matyrobbrt/gml/mod/PackMCMetaVersionsGetter.groovy#L19

Using a simple hard-coded values fixes the issue.

**Comment by Matyrobbrt** [comment]
This issue is caused by https://github.com/Matyrobbrt/GroovyModLoader/blob/main/src/mod/groovy/com/matyrobbrt/gml/mod/PackMCMetaVersionsGetter.groovy not getting remapped.

**Comment by PaintNinja** [comment]
How do you propose we fix this? `@CompileDynamic` might work but would be slower, or we could simply hardcode the values and manually change them each MC release as needed. Or is this a bug with the mod sourceset unexpectedly not being remapped?

**Comment by Matyrobbrt** [comment]
Neither options are going to fix it, the property syntax uses dynamic calls, and the metaclass remapping is not yet set up that early. The fix is to make that class use Java.

**Comment by PaintNinja** [comment]
https://github.com/Matyrobbrt/GroovyModLoader/commit/98c127c9f514d13a2ae0ddaa46b1f01421a47abd has fixed it in production, but now crashes in dev.
